# Generated by Django 2.2 on 2019-05-24 09:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0002_auto_20190524_1443'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='parnet',
            new_name='parent',
        ),
    ]
